version: '3'

services:
  api:
    build: ./api
    ports:
      - "8002:8002"
    volumes:
      - ./api:/app
      - ./data:/app/data
      - ./models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build: ./streamlit_app
    ports:
      - "8502:8502"
    volumes:
      - ./streamlit_app:/app
      - ./data:/app/data
    environment:
      - API_URL=http://api:8002
    depends_on:
      - api
